# Generated by Django 4.2.1 on 2023-05-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=50)),
                ('u_email', models.CharField(max_length=50)),
                ('u_number', models.CharField(max_length=50)),
                ('u_address', models.CharField(max_length=50)),
                ('u_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reg_tb',
            },
        ),
    ]
